# Generated by Django 4.2 on 2025-10-13 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли?')),
                ('hired_date', models.DateField(auto_now_add=True, verbose_name='Дата приёма на работу')),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
            ],
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='workers_wor_is_acti_bfc83b_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['position'], name='workers_wor_positio_86a69d_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['email'], name='workers_wor_email_af9293_idx'),
        ),
    ]
