# Generated by Django 4.2 on 2025-10-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='worker',
            name='workers_wor_email_af9293_idx',
        ),
    ]
